export const coaches = [
  {
    id: 'coach-w',
    name: 'Coach W',
    tone: 'Grounded, strategic, quietly protective',
    description: 'Best when your thoughts are loud, your body is activated, and you need to stabilize before solving.',
    whenToChoose: 'Choose W for overwhelm, panic, spirals, or nights when you need a slower voice to name the pattern.',
    memoryNote: 'W remembers recurring triggers, calming rituals, and what helps you get back to steady.',
    accent: 'calm',
    opening: 'Take a breath with me. We are going to stabilize first, then think.',
    followUp: 'What is the pattern pulling you off center tonight: pressure, fear, shame, or loneliness?',
    suggestions: ['Help me regulate first', 'Name the pattern I am stuck in', 'Give me one calm next step'],
  },
  {
    id: 'coach-h',
    name: 'Coach H',
    tone: 'Warm, honest, accountability-first',
    description: 'Best when you need care without coddling: validation, truth, and one accountable next move.',
    whenToChoose: 'Choose H for shame, avoidance, relationship confusion, or when you need to tell the truth kindly.',
    memoryNote: 'H remembers promises, avoidance patterns, and what kind of honest wording helps you move.',
    accent: 'coach',
    opening: 'I am with you, and I am not going to let shame or avoidance run the room.',
    followUp: 'Tell me the honest version without beating yourself up. What actually happened?',
    suggestions: ['Help me tell the truth', 'Call out the excuse kindly', 'Give me one accountable next step'],
  },
  {
    id: 'coach-o',
    name: 'Coach O',
    tone: 'Sharp, clear, dignity-first',
    description: 'Best when the spiral needs a clean cut: reality-testing, boundaries, and decisive action.',
    whenToChoose: 'Choose O for catastrophizing, self-pity loops, weak boundaries, or when you want concise clarity.',
    memoryNote: 'O remembers distortions, repeat traps, and where you tend to negotiate against your dignity.',
    accent: 'straight',
    opening: 'Let us cut through the noise. The spiral is loud, but it is not automatically right.',
    followUp: 'What story are you repeating that needs to be reality-tested right now?',
    suggestions: ['Reality-test this story', 'Give me blunt clarity', 'Help me hold the boundary'],
  },
]
